# wslfetch
# Autogenerated from man page /usr/share/man/man1/wslfetch.1.gz
complete -c wslfetch -s h -l help --description '.'
complete -c wslfetch -s v -l version --description '.'
complete -c wslfetch -s l -l line --description '.'
complete -c wslfetch -s s -l splash -l 'splash\'' --description 'SEE ALSO https://github.'

