# wslsys
# Autogenerated from man page /usr/share/man/man1/wslsys.1.gz
complete -c wslsys -s h -l help --description '.'
complete -c wslsys -s v -l version --description '.'
complete -c wslsys -s U -l uptime --description '.'
complete -c wslsys -s b -l branch --description '.'
complete -c wslsys -s B -l build --description '.'
complete -c wslsys -o fB -l full-build --description '.'
complete -c wslsys -s K -l kernel --description '.'
complete -c wslsys -s R -l release --description '.'
complete -c wslsys -s P -l package --description 'SEE ALSO https://github.'

