# wslupath
# Autogenerated from man page /usr/share/man/man1/wslupath.1.gz
complete -c wslupath -s O -l original --description '.'
complete -c wslupath -s d -l doubledash-dir --description '.'
complete -c wslupath -s r -l reg-data -s R --description 'System Path.'
complete -c wslupath -s D -l desktop --description '.'
complete -c wslupath -s A -l appdata --description '.'
complete -c wslupath -s T -l temp --description '.'
complete -c wslupath -s S -l sysdir --description '.'
complete -c wslupath -s W -l windir --description '.'
complete -c wslupath -s s -l start-menu --description '.'
complete -c wslupath -o su -l startup --description '.'
complete -c wslupath -s H -l home --description '.'
complete -c wslupath -s P -l program-files --description 'Other Options.'
complete -c wslupath -s h -l help --description '.'
complete -c wslupath -s v -l version --description '.'
complete -c wslupath -l avail-reg --description 'SEE ALSO https://github.'

