# wslview
# Autogenerated from man page /usr/share/man/man1/wslview.1.gz
complete -c wslview -s h -l help --description '.'
complete -c wslview -s v -l version --description '.'
complete -c wslview -s u -l unregister --description '.'
complete -c wslview -s r -l register --description 'SEE ALSO https://github.'

