# wslvar
# Autogenerated from man page /usr/share/man/man1/wslvar.1.gz
complete -c wslvar -s s -l sys --description '.'
complete -c wslvar -s l -l shell --description 'Other Options.'
complete -c wslvar -s h -l help --description '.'
complete -c wslvar -s v -l version --description '.'
complete -c wslvar -s S -l getsys --description '.'
complete -c wslvar -s L -l getshell --description 'SEE ALSO https://github.'

